version: '3.3'
services:
  freqServ-4:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: 4SmaRsi2
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "83:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SmaRSIdos
      
    #deploy:
      #mode: replicated
      #replicas: 1
      #placement:
        #constraints:
          #- node.role == manager
           
      #restart_policy:
        #condition: on-failure
        #delay: 5s
         
      #labels:
       #- 'http.routers.freqtrade.tls=true'
       #- 'http.routers.freqtrade.rule=Host(`freqtrade.localhost`)'
       #- 'http.services.freqtrade.loadbalancer.server.port=8080'

